### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sconstantinides** [Vestorly/ember-cli-emblem#13]
I believe it should now be simply: `ember install ember-cli-emblem-hbs-printer`

FYI I'm using version: 0.2.3

**Comment by buschtoens** [comment]
[As per the docs](http://www.ember-cli.com/#using-ember-cli), yes it would be `ember install <addon-name>`. However, the name of this project changed to `ember-cli-emblem`.

The correct command would now be `ember install ember-cli-emblem`. Care to submit a PR? :stuck_out_tongue_winking_eye:

**Comment by sconstantinides** [comment]
Done :)

**Comment by buschtoens** [comment]
👍
