### ISSUE TITLE
Blueprints for generating a component inside an addon no longer correct in ember-cli 0.2.5

### ISSUE THREAD

**Issue by coladarci** [Vestorly/ember-cli-emblem#17]
Version:
```
ember -v
version: 0.2.5
node: 0.12.1
npm: 2.10.0
```

When running `ember g component pro-button` w/out emblem installed:
```
  create addon/components/pro-button.js
  create addon/templates/components/pro-button.hbs
installing
  create tests/unit/components/pro-button-test.js
installing
  create app/components/pro-button.js
```

When running `ember g component pro-button` with emblem installed:

```
version: 0.2.5
installing
  create app/components/pro-button.js
  create app/templates/components/pro-button.emblem
installing
  create tests/unit/components/pro-button-test.js
installing
[?] Overwrite app/components/pro-button.js? Yes, overwrite
  overwrite app/components/pro-button.js
```

Note that the file structure is different, and there's a strange prompt to over-write pro-button.js when it didn't exist before I ran the generate (I tried a few times since it seemed strange..)

**Comment by jsec** [comment]
Ah I think I see what the issue is.

Looking at the default ember-cli blueprints, the component blueprint is generated into `files/__root__`, while the component blueprint here gets generated into `files/app`.

I should be able to take a deeper look into this in the next couple of days, if the maintainers are ok with it.

**Comment by joebartels** [comment]
@jsec yeah totally!  Ill also reserve some time this weekend myself to take a look so feel free to drop a line or update this issue (or PR :wink:) w/ your notes. thhanks!

**Comment by jsec** [comment]
OK, just confirmed that was indeed the issue.

I also noticed digging into it that the toggle for enabling/disabling blueprints is no longer in the main `index.js` file. I had originally included it, but I think it got lost in translation squashing my original PR's commits. I'll add that back in.

I should have a PR up within an hour or so.

**Comment by coladarci** [comment]
Thanks @jsec - much appreciated..

**Comment by joebartels** [comment]
@jsec awesome response time! thanks again :tanabata_tree:

**Comment by coladarci** [comment]
@joebartels - can you tag a release on NPM? Looking forward to trying this out!

**Comment by joebartels** [comment]
@coladarci done! thanks for reminder :smile:

**Comment by coladarci** [comment]
everything is working! Thanks!
