### ISSUE TITLE
Support new HTMLBars-style bound attributes

### ISSUE THREAD

**Issue by joshuaconner** [Vestorly/ember-cli-emblem#21]
Got the following deprecation a lot when I upgraded to Ember 1.13:

```
Ember 1.13: DEPRECATION: The `bind-attr` helper is deprecated in favor of HTMLBars-style bound attributes.
```

I'm assuming it's because emblem still outputs `{{bind-attr}}`. Is there a workaround in place? Thanks!

**Comment by joshuaconner** [comment]
whoops wrong repo, sorry!

**Comment by joebartels** [comment]
![you didnt see anything](http://25.media.tumblr.com/b7275f174fd41f8e6b71bc3e3296139c/tumblr_mia5bauxj81qmgkt8o1_250.gif)
