### ISSUE TITLE
Extra "/" in generated component tests

### ISSUE THREAD

**Issue by andrewtimberlake** [Vestorly/ember-cli-emblem#32]
> This was redirected here from [emblem.js #259](https://github.com/machty/emblem.js/issues/259#issuecomment-16734609)

When running `ember g component test-component --pod` the generated test has an extra slash in each handlebars component statement.
Instead of 
```javascript
this.render(hbs`{{test-component}}`);
//...
this.render(hbs`
  {{#test-component}}
    template block text
  {{/test-component}}
`);
```
the output is
```javascript
this.render(hbs`{{/test-component}}`);
//...
this.render(hbs`
  {{#/test-component}}
    template block text
  {{//test-component}}
`);
```
I only get this issue on projects that use emblem.

Environment:
Ember      : 2.2.0
Ember Data : 2.2.0
jQuery     : 2.1.4

**Comment by joebartels** [comment]
Ah thanks for sending that over here. 
I'm working inside a project with these versions atm, and cannot repro.
Ember-Cli 1.13.8
Ember 1.13.8
Ember Data 1.13.15

So possibly something ember/ember-cli 2.x 

Could you share your ember-cli-emblem version from **node_modules/ember-cli-emblem/package.json**
and also which ember-cli version you're using @andrewtimberlake

**Comment by andrewtimberlake** [comment]
It was doing it with
Ember-cli 1.13.13
Ember 2.2.0

Also doing it in
Ember 2.3.0-beta.3
Ember-cli 2.2.0-beta.2

Both with ember-cli-emblem 0.3.1

Andrew

**Comment by chris-roerig** [comment]
I'm having this issue as well.

here are my devDependencies

https://gist.github.com/chris-roerig/d28546858f26b1da0606

**Comment by joebartels** [comment]
Thanks for sharing the dependencies. Will test with those

**Comment by buschtoens** [comment]
Relevant blueprint from ember-cli: https://github.com/ember-cli/ember-cli/blob/master/blueprints/component-test/files/tests/__testType__/__path__/__test__.js

Seems like installing ember-cli-emblem alters the `componentPathName`.

**Comment by buschtoens** [comment]
I suspect [these lines](https://github.com/ember-cli/ember-cli/blob/164cc0e104bb69d685fb8ec3ff187db8fe9a865f/blueprints/component-test/index.js#L45-L47) are causing the error:

```js
if (options.pod && options.path !== 'components' && options.path !== '') {
  componentPathName = [options.path, dasherizedModuleName].join('/');
}
```

**Comment by buschtoens** [comment]
Yup, `options.path` is `undefined` which is not `!== ''` but is coerced as an empty string.

**Comment by buschtoens** [comment]
I fixed it. Prepping a PR.
