### ISSUE TITLE
use emblem inside an addon

### ISSUE THREAD

**Issue by Leooo** [Vestorly/ember-cli-emblem#39]
(copy of https://github.com/machty/emblem.js/issues/273)

Hello, is this a normal use case and is it possible to use emblem inside of an addon? Right now using an addon building components using a `layout` syntax to fetch the templates, and it doesn't seem that the template.embl are processed at all?

myApp/addon/components/my-component/controller.js:
`````
import Ember from 'ember';
import DS from 'ember-data';
import layout from './template';

export default Ember.Component.extend({
  layout,
  ..
})
`````
myApp/addon/components/my-component/template.embl:
=> not processed

myApp/addon/components/my-component/template.hbs:
=> processed

package.json:
`````
    "ember-cli-emblem": "0.4.0",
`````

**Comment by Leooo** [comment]
Working now, only had to move ember-cli-emblem dependency from devDependencies to dependencies inside the addon,

**Comment by joebartels** [comment]
👍 thanks for updating with your sol'n @Leooo
