### ISSUE TITLE
Feature request: blueprints

### ISSUE THREAD

**Issue by ballPointPenguin** [Vestorly/ember-cli-emblem#4]
It would be great if emblem blueprints were provided for ember-cli template generators.

**Comment by buschtoens** [comment]
+1

**Comment by mixonic** [comment]
Seems pretty easy, the [coffeescript addon](https://github.com/kimroen/ember-cli-coffeescript) is a good example of how to do this.

**Comment by buschtoens** [comment]
So basically [this](https://github.com/kimroen/ember-cli-coffeescript/blob/5c925673617d0d6277711a0ea1d51c5c5d31ecc1/index.js#L32-36) and [this](https://github.com/kimroen/ember-cli-coffeescript/tree/5c925673617d0d6277711a0ea1d51c5c5d31ecc1/blueprints)?

**Comment by aliaksandrb** [comment]
Also vote up for this nice feature! :+1:

**Comment by ballPointPenguin** [comment]
Might take a stab at it this weekend...

**Comment by jsec** [comment]
I took a stab at this.

Check out PR #12

**Comment by buschtoens** [comment]
I guess #12 closed this? :tada:

**Comment by joebartels** [comment]
why not :tanabata_tree:
