### ISSUE TITLE
Long term maintainer

### ISSUE THREAD

**Issue by alexparker** [Vestorly/ember-cli-emblem#61]
Really hoping that ember-cli-emblem doesn't go away anytime soon, so just wanted to make this in an effort to know what the the long-term support plan for ember-cli-emblem is.

Seeing this comment: https://github.com/Vestorly/ember-cli-emblem/issues/55#issuecomment-362391196
I started to get a little concerned of the long-term maintenance of the addon.

Also it seems there is an org to adopt addons here if a new maintainer is found that wants to adopt the addon: https://github.com/adopted-ember-addons

**Comment by Gaurav0** [comment]
I would suggest discussing with @joebartels at Vestorly about transferring ember-cli-emblem to a new maintainer. As for myself, I no longer work for Vestorly.

**Comment by thec0keman** [comment]
FWIW I'd be happy to help with the maintenance of this addon

**Comment by thec0keman** [comment]
CC @joebartels

**Comment by thec0keman** [comment]
Hey, I just wanted to add that I am going to help maintain this addon now.  We still need to get some issues resolved with NPM before we can push new versions there, but I am going to close this for now.

Thanks!
